### PR TITLE
Fix minio version to 7.2.0

### PR DESCRIPTION
**Pull request by shubhadeepd**
- Avoid pulling in latest version of minio to fix a dependency issue caused by the latest version
- Fixes https://github.com/NVIDIA/GenerativeAIExamples/issues/19

### CODE REVIEW

**Comment by pranjaldoshi96** [comment]
LGTM!!

**Review by jliberma — APPROVED** [review]
lgtm

**Comment by jliberma** [comment]
@shubhadeepd  @sumitkbh  -- Launchpad pulls from v0.1.0.  So does the Helm chart. Please confirm that this fix will fix it in all the tagged branches as well as main.

**Comment by robdaly** [comment]
> @shubhadeepd  @sumitkbh  -- Launchpad pulls from v0.1.0.  So does the Helm chart. Please confirm that this fix will fix it in all the tagged branches as well as main. 

Or, provide the tagged version  for LaunchPad to target for future trial requests.

**Comment by shubhadeepd** [comment]
> > @shubhadeepd  @sumitkbh  -- Launchpad pulls from v0.1.0.  So does the Helm chart. Please confirm that this fix will fix it in all the tagged branches as well as main.
> 
> Or, provide the tagged version for LaunchPad to target for future trial requests.

@robdaly can you use the main branch for now? These types of breaking changes (due to third-party libraries) may be frequent, and it isn't easy to maintain/backport the fix in every tagged release branch. We can ensure the main branch will be always functional. You can use the v0.3.0 branch which will be forked from main around January 20th with this fix, and use the main branch till then.

**Pull request merged**
